# Generated by Django 3.1.4 on 2020-12-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songrank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['ranking']},
        ),
    ]
