# Generated by Django 3.1.4 on 2021-01-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrank', '0003_remove_member_initials'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['-ranking']},
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('done', models.BooleanField(default=False)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songrank.song')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='songrank.pipelinetemplate')),
            ],
            options={
                'unique_together': {('song', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PhaseDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField()),
                ('buffer_days', models.IntegerField(default=1)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream_phase_descriptors', to='songrank.phasedescriptor')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_descriptors', to='songrank.pipelinetemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'name'), ('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='songrank.phasedescriptor')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='songrank.pipeline')),
            ],
            options={
                'ordering': ['due'],
                'unique_together': {('pipeline', 'descriptor')},
            },
        ),
    ]
