# Generated by Django 3.1.4 on 2021-04-12 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrank', '0005_pipeline_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('demo', models.URLField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('writers', models.ManyToManyField(related_name='choppers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('chopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescues', to='songrank.chopper')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'chopper')},
            },
        ),
        migrations.CreateModel(
            name='Chop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chops', to='songrank.chopper')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'chopper')},
            },
        ),
    ]
