# Generated by Django 3.1.4 on 2021-04-13 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrank', '0007_member_rankings_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongChop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chops', to='songrank.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_chops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('song', 'user')},
            },
        ),
    ]
