# Generated by Django 3.1.4 on 2021-04-14 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrank', '0009_choppercomment_songcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chopper',
            name='rescuers',
            field=models.ManyToManyField(related_name='rescue_choppers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Rescue',
        ),
    ]
